### ISSUE TITLE
Errors when copying ABS Demo to New Project and Test Playing.

### ISSUE THREAD

**Issue by shadowsatey** [quxios/Quasi-MV-ABS-Demo#1]
![abs fail](https://cloud.githubusercontent.com/assets/20080006/16253482/182441c8-37f4-11e6-8abe-245020487190.PNG)
![abs fail 2](https://cloud.githubusercontent.com/assets/20080006/16253483/18ef278a-37f4-11e6-810e-ac264db64a1f.PNG)

These are the errors I get before playing the Demo Game.

**Comment by quxios** [comment]
Thanks for informing me. Feel free to grab the new js file:
https://github.com/quasixi/Quasi-MV-ABS-Demo/blob/master/js/plugins/QuasiABS.js

I didn't change the version number on it. since it's basically the same thing. But for some reason when I uploaded it to github a line of code was deleted which caused those errors.
