### ISSUE TITLE
A couple of bugs

### ISSUE THREAD

**Issue by MeltageTab** [quxios/Quasi-MV-ABS-Demo#3]
Hello once again,

After you fixed the bug with saving/loading I managed to find a couple more bugs while working on my game. I took some time to test many different things and it seems there are several different problems with pausing/saving the game.

I made a video with labels to illustrate the glitches. All of them should be easy to reproduce for console output. Link to the vid - https://www.youtube.com/watch?v=2P86wXhHrS8

**Comment by quxios** [comment]
Thanks for making a video!
For the first bug, are you using the sample class change common event I included in the demo? If you are, then that common event requires my Quasi QEvent plugin to work:
https://github.com/quasixi/Quasi-MV-ABS-Demo/blob/master/js/plugins/QuasiQEvents.js
If you do have that plugin on. Then push F8 to open the console log, and show show me the error that displays in the console log.

As for the saving / loading bugs. The enemies were intended to be fully restored. But the other bugs you reported weren't intentional and I'll look into them.

**Comment by MeltageTab** [comment]
Yes, I used your sample class change. Nothing was changed in the skill/common event and the plugin is installed and enabled. Here's the console log.

![abs](https://cloud.githubusercontent.com/assets/20156905/16447641/c240b354-3ded-11e6-8d52-f59bfbac30c6.png)

**Comment by quxios** [comment]
Any chance you are using other plugins besides mine? Because I just retried the ABS demo, and that common event ran just fine.
Also from that error it looks like you have a plugin that overrides the .changeClass function and made it into an object instead. Which is very very bad.

**Comment by MeltageTab** [comment]
I didn't change anything in the plugins, should be the default list in the order it's set in the demo.

![abs](https://cloud.githubusercontent.com/assets/20156905/16451537/fb5c5236-3e03-11e6-9f4b-ec922e6b43f3.png)

**Comment by ttnghia195** [comment]
I down the demo project but it error
![image](https://user-images.githubusercontent.com/19924565/27983801-961fba8a-63ef-11e7-94fc-0a7552852d15.png)
![image](https://user-images.githubusercontent.com/19924565/27983802-99b7bd64-63ef-11e7-9549-1fc1541cbe05.png)

**Comment by quxios** [comment]
@ttnghia195 All Quasi plugins should be considered Dead. Consider using the QPlugins instead.
https://github.com/quxios/QMV-Master-Demo
https://github.com/quxios/QMV-ABS-Demo

**Comment by ttnghia195** [comment]
@quxios Thank you!!!
